/*
 * KomMonitor Data Access API
 * Definition einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.n52.kommonitor.datamanagement.api.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}