/*
 * KomMonitor Data Import API
 * erster Entwurf einer Daten-Import-API, die den Import räumlicher Daten (SpatialUnits, Georesources und Indicators) von beliebigen Datenquellen und Koordinatenreferenzsystemen ermöglicht.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.n52.kommonitor.datamanagement.client;

import org.n52.kommonitor.importer.models.ImportIndicatorPOSTInputType;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IndicatorsApi
 */
@Ignore
public class IndicatorsApiTest {

    private final IndicatorsApi api = new IndicatorsApi();

    
    /**
     * Import a new indicator dataset
     *
     * Import an indicator dataset for a certain period of time and spatial unit/level. Parses Input source, extracts relevant data, performs schema mapping to KomMonitor data model and calls POST /indicators of KomMonitor Data Management API
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void importIndicatorTest() {
        ImportIndicatorPOSTInputType indicatorData = null;
        api.importIndicator(indicatorData);

        // TODO: test validations
    }
    
}
