/*
 * KomMonitor Data Import API
 * erster Entwurf einer Daten-Import-API, die den Import räumlicher Daten (SpatialUnits, Georesources und Indicators) von beliebigen Datenquellen und Koordinatenreferenzsystemen ermöglicht.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.n52.kommonitor.datamanagement.client;

import org.n52.kommonitor.importer.models.ImportSpatialUnitPOSTInputType;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SpatialUnitsApi
 */
@Ignore
public class SpatialUnitsApiTest {

    private final SpatialUnitsApi api = new SpatialUnitsApi();

    
    /**
     * Import a new spatial-unit
     *
     * Import a new spatial unit for a certain period of time. Parses Input source, extracts relevant data, performs schema mapping to KomMonitor data model and calls POST /spatial-units of KomMonitor Data Management API
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void importSpatialUnitTest() {
        ImportSpatialUnitPOSTInputType featureData = null;
        api.importSpatialUnit(featureData);

        // TODO: test validations
    }
    
}
