package org.n52.kommonitor.models;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.n52.kommonitor.models.ClassificationTypeEnum;
import org.springframework.lang.Nullable;
import org.openapitools.jackson.nullable.JsonNullable;
import java.io.Serializable;
import java.time.OffsetDateTime;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import jakarta.annotation.Generated;

/**
 * AbstractClassificationMappingType
 */

@JsonIgnoreProperties(
  value = "classificationType", // ignore manually set classificationType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the classificationType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "classificationType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = QualitativeClassificationMappingType.class, name = "QUALITATIVE"),
  @JsonSubTypes.Type(value = DefaultClassificationMappingType.class, name = "QUANTITATIVE")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-07-23T12:40:19.067418300+02:00[Europe/Berlin]", comments = "Generator version: 7.23.0")
public class AbstractClassificationMappingType implements Serializable {

  private static final long serialVersionUID = 1L;

  private @Nullable ClassificationTypeEnum classificationType;

  private String colorBrewerSchemeName;

  private BigDecimal numClasses;

  public AbstractClassificationMappingType() {
    super();
  }

  /**
   * Constructor with only required parameters
   */
  public AbstractClassificationMappingType(String colorBrewerSchemeName, BigDecimal numClasses) {
    this.colorBrewerSchemeName = colorBrewerSchemeName;
    this.numClasses = numClasses;
  }

  public AbstractClassificationMappingType classificationType(@Nullable ClassificationTypeEnum classificationType) {
    this.classificationType = classificationType;
    return this;
  }

  /**
   * Get classificationType
   * @return classificationType
   */
  @Valid 
  @Schema(name = "classificationType", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("classificationType")
  public @Nullable ClassificationTypeEnum getClassificationType() {
    return classificationType;
  }

  @JsonProperty("classificationType")
  public void setClassificationType(@Nullable ClassificationTypeEnum classificationType) {
    this.classificationType = classificationType;
  }

  public AbstractClassificationMappingType colorBrewerSchemeName(String colorBrewerSchemeName) {
    this.colorBrewerSchemeName = colorBrewerSchemeName;
    return this;
  }

  /**
   * the name of the colorBrewer color scheme used to define the colors for classification (see project http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3 for colorSchemes). Set to 'INDIVIDUAL' if colors are set arbitrarily.
   * @return colorBrewerSchemeName
   */
  @NotNull 
  @Schema(name = "colorBrewerSchemeName", description = "the name of the colorBrewer color scheme used to define the colors for classification (see project http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3 for colorSchemes). Set to 'INDIVIDUAL' if colors are set arbitrarily.", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("colorBrewerSchemeName")
  public String getColorBrewerSchemeName() {
    return colorBrewerSchemeName;
  }

  @JsonProperty("colorBrewerSchemeName")
  public void setColorBrewerSchemeName(String colorBrewerSchemeName) {
    this.colorBrewerSchemeName = colorBrewerSchemeName;
  }

  public AbstractClassificationMappingType numClasses(BigDecimal numClasses) {
    this.numClasses = numClasses;
    return this;
  }

  /**
   * the number of classes
   * minimum: 1
   * maximum: 9
   * @return numClasses
   */
  @NotNull @Valid @DecimalMin(value = "1") @DecimalMax(value = "9") 
  @Schema(name = "numClasses", description = "the number of classes", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("numClasses")
  public BigDecimal getNumClasses() {
    return numClasses;
  }

  @JsonProperty("numClasses")
  public void setNumClasses(BigDecimal numClasses) {
    this.numClasses = numClasses;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AbstractClassificationMappingType abstractClassificationMappingType = (AbstractClassificationMappingType) o;
    return Objects.equals(this.classificationType, abstractClassificationMappingType.classificationType) &&
        Objects.equals(this.colorBrewerSchemeName, abstractClassificationMappingType.colorBrewerSchemeName) &&
        Objects.equals(this.numClasses, abstractClassificationMappingType.numClasses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(classificationType, colorBrewerSchemeName, numClasses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbstractClassificationMappingType {\n");
    sb.append("    classificationType: ").append(toIndentedString(classificationType)).append("\n");
    sb.append("    colorBrewerSchemeName: ").append(toIndentedString(colorBrewerSchemeName)).append("\n");
    sb.append("    numClasses: ").append(toIndentedString(numClasses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(@Nullable Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

