/*
 * KomMonitor Data Access API
 * erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.n52.kommonitor.datamanagement.api.client;

import org.junit.Test;
import org.junit.Ignore;
import org.n52.kommonitor.models.RoleInputType;
import org.n52.kommonitor.models.RoleOverviewType;

import java.util.List;

/**
 * API tests for RolesApi
 */
@Ignore
public class RolesApiTest {

    private final RolesApi api = new RolesApi();

    
    /**
     * Register a new role
     *
     * Add/Register a role
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addRoleTest() {
        RoleInputType roleData = null;
        api.addRole(roleData);

        // TODO: test validations
    }
    
    /**
     * Delete the role
     *
     * Delete the role
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRoleTest() {
        String roleId = null;
        api.deleteRole(roleId);

        // TODO: test validations
    }
    
    /**
     * retrieve information about the selected role
     *
     * retrieve information about the selected role
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRoleByIdTest() {
        String roleId = null;
        RoleOverviewType response = api.getRoleById(roleId);

        // TODO: test validations
    }
    
    /**
     * retrieve information about available roles
     *
     * retrieve information about available roles
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRolesTest() {
        List<RoleOverviewType> response = api.getRoles();

        // TODO: test validations
    }
    
    /**
     * Modify role information
     *
     * Modify role information
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRoleTest() {
        String roleId = null;
        RoleInputType roleData = null;
        api.updateRole(roleId, roleData);

        // TODO: test validations
    }
    
}
