/*
 * KomMonitor Data Access API
 * erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: christian.danowski-buhren@hs-bochum.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.n52.kommonitor.datamanagement.api.legacy.client;

import java.io.IOException;
import java.math.BigDecimal;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.n52.kommonitor.datamanagement.api.legacy.ApiClient;
import org.n52.kommonitor.models.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.client.RestClientTest;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.web.client.ExpectedCount;
import org.springframework.test.web.client.MockRestServiceServer;
import org.springframework.web.client.RestTemplate;

import java.util.Arrays;
import java.util.List;

import static org.springframework.test.web.client.match.MockRestRequestMatchers.method;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.requestTo;
import static org.springframework.test.web.client.response.MockRestResponseCreators.withStatus;

/**
 * API tests for SpatialUnitsApi
 */
@RestClientTest(SpatialUnitsApi.class)
@ContextConfiguration(classes = {ApiClient.class, SpatialUnitsApi.class, RestTemplate.class})
public class SpatialUnitsApiIT {

    private static final String BASE_PATH = "http://localhost:8085/management";

    @Autowired
    private SpatialUnitsApi api;

    @Autowired
    private RestTemplate restTemplate;

    @Autowired
    private ObjectMapper mapper;

    private MockRestServiceServer mockServer;

    @BeforeEach
    private void init() throws IOException {
        api.getApiClient().setBasePath(BASE_PATH);
        mockServer = MockRestServiceServer.createServer(restTemplate);
    }


    /**
     * Add a new spatial-unit
     * <p>
     * Add/Register a spatial unit for a certain period of time
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addSpatialUnitAsBodyTest() {
        HttpHeaders headers = new HttpHeaders();
        mockServer.expect(ExpectedCount.once(),
                requestTo(BASE_PATH + "/spatial-units"))
                .andExpect(method(HttpMethod.POST))
                .andRespond(withStatus(HttpStatus.CREATED)
                );

        api.addSpatialUnitAsBodyWithHttpInfo(Mockito.mock(SpatialUnitPOSTInputType.class));

        mockServer.verify();
    }

    /**
     * Delete the features/contents of the selected spatial-unit
     * <p>
     * Delete the features/contents of the selected spatial-unit
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @Disabled
    public void deleteSpatialUnitByIdTest() {
        String spatialUnitId = null;
        api.deleteSpatialUnitById(spatialUnitId);

        // TODO: test validations
    }

    /**
     * Delete the features/contents of the selected spatial-unit, year and month
     * <p>
     * Delete the features/contents of the selected spatial-unit, year and month
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @Disabled
    public void deleteSpatialUnitByIdAndYearAndMonthTest() {
        String spatialUnitId = null;
        BigDecimal year = null;
        BigDecimal month = null;
        BigDecimal day = null;
        api.deleteSpatialUnitByIdAndYearAndMonth(spatialUnitId, year, month, day);

        // TODO: test validations
    }

    /**
     * retrieve all feature entries for all applicable periods of validity for the selected spatial unit/level (hence might contain each feature multiple times if they exist for different periods of validity)
     * <p>
     * retrieve all feature entries for all applicable periods of validity for the selected spatial unit/level (hence might contain each feature multiple times if they exist for different periods of validity)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @Disabled
    public void getAllSpatialUnitFeaturesByIdTest() {
        String spatialUnitId = null;
        String simplifyGeometries = null;
        String response = api.getAllSpatialUnitFeaturesById(spatialUnitId, simplifyGeometries);

        // TODO: test validations
    }

    /**
     * retrieve information about available features of different spatial units/levels
     * <p>
     * retrieve information about available features of different spatial units/levels
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSpatialUnitsTest() throws JsonProcessingException {
        SpatialUnitOverviewType georesource = new SpatialUnitOverviewType();
        georesource.setSpatialUnitId("testId");

        mockServer.expect(ExpectedCount.once(),
                requestTo(BASE_PATH + "/spatial-units"))
                .andExpect(method(HttpMethod.GET))
                .andRespond(withStatus(HttpStatus.OK)
                        .contentType(MediaType.APPLICATION_JSON)
                        .body(mapper.writeValueAsString(Arrays.asList(georesource)))
                );

        List<SpatialUnitOverviewType> response = api.getSpatialUnits();

        mockServer.verify();
        Assertions.assertEquals(1, response.size());
        Assertions.assertEquals("testId", response.get(0).getSpatialUnitId());
    }

    /**
     * retrieve information about available features of the selected spatial unit/level
     * <p>
     * retrieve information about available features of the selected spatial unit/level
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSpatialUnitsByIdTest() {
        String resourceId = "testId";

        HttpHeaders headers = new HttpHeaders();
        mockServer.expect(ExpectedCount.once(),
                requestTo(BASE_PATH + "/spatial-units/" + resourceId))
                .andExpect(method(HttpMethod.PUT))
                .andRespond(withStatus(HttpStatus.OK)
                );

        api.updateSpatialUnitAsBodyWithHttpInfo(resourceId, Mockito.mock(SpatialUnitPUTInputType.class));

        mockServer.verify();
    }

    /**
     * retrieve the features according to the selected spatial unit/level and selected year and month as GeoJSON
     * <p>
     * retrieve the features according to the selected spatial unit/level and selected year and month as GeoJSON
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @Disabled
    public void getSpatialUnitsByIdAndYearAndMonthTest() {
        String spatialUnitId = null;
        BigDecimal year = null;
        BigDecimal month = null;
        BigDecimal day = null;
        String simplifyGeometries = null;
        byte[] response = api.getSpatialUnitsByIdAndYearAndMonth(spatialUnitId, year, month, day, simplifyGeometries);

        // TODO: test validations
    }

    /**
     * retrieve the JSON schema for the selected spatial unit/level
     * <p>
     * retrieve the JSON schema for the selected spatial unit/level. The JSON schema indicates the property structure of the dataset.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @Disabled
    public void getSpatialUnitsSchemaByIdTest() {
        String spatialUnitId = null;
        String response = api.getSpatialUnitsSchemaById(spatialUnitId);

        // TODO: test validations
    }

    /**
     * Modify/Update the features of the selected spatial-unit
     * <p>
     * Modify/Update the features of the selected spatial-unit. The interface expects a full upload of all geometries for the spatial unit. Internally, those geometries are compared to the existing ones to mark &#39;old&#39; geometries that are no longer in use as outdated. Hence, each geometric object is only persisted once and its use is controlled by time validity marks.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @Disabled
    public void updateSpatialUnitAsBodyTest() {
        String spatialUnitId = null;
        SpatialUnitPUTInputType featureData = null;
        api.updateSpatialUnitAsBody(spatialUnitId, featureData);

        // TODO: test validations
    }

    /**
     * Modify/Update the metadata of the selected spatial-unit
     * <p>
     * Modify/Update the metadata of the selected spatial-unit. This replaces the formerly stored metadata.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    @Disabled
    public void updateSpatialUnitMetadataAsBodyTest() {
        String spatialUnitId = null;
        SpatialUnitPATCHInputType metadata = null;
        api.updateSpatialUnitMetadataAsBody(spatialUnitId, metadata);

        // TODO: test validations
    }

}
