server:
  port: 8087
  contextPath: /import
spring:
  application:
    name: kommonitor-import-api
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
