server:
  port: 8087
spring:
  application:
    name: kommonitor-import-api
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    org.n52.kommonitor: DEBUG
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
kommonitor:
  importer:
    datamanagement-api-url: "http://localhost:8085/management"
    file-storage-location: "/tmp/kommonitor"
  swagger-ui:
    # base-path: /importer
    # do not use real values in production environment!!!
    security:
      client-id: kommonitor-importer
      secret: secret
keycloak:
  enabled: true
  realm: kommonitor
  auth-server-url: http://localhost:8080/auth
  resource: kommonitor-importer
  bearer-only: true
  autodetect-bearer-only: false
  ssl-required: external
  public-client: false
  credentials:
    secret: secret
  cors: true
  cors-allowed-methods: "*"
  securityConstraints[0]:
    authRoles[0]: administrator
    securityCollections[0]:
      name: protected
      patterns[0]: /importer/*