server:
  port: 8087
  forward-headers-strategy: FRAMEWORK
spring:
  application:
    name: kommonitor-import-api
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
    session:
      timeout: 1m
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/kommonitor
          jwk-set-uri: http://keycloak:8080/realms/kommonitor/protocol/openid-connect/certs
  mustache:
    check-template-location: false
logging:
  level:
    org.n52.kommonitor: DEBUG
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
kommonitor:
  importer:
    datamanagement-api-url: "http://localhost:8085/management"
    geocoder-api-url: "https://geocoder.fbg-hsbo.de/geocoder"
    file-storage-location: "/tmp/kommonitor"
  swagger-ui:
    # Use the next two parameters if you run the API behind a reverse proxy
    # Host address of the reverse proxy
    # Path mapping for this API in the reverse proxy
    server: "http://localhost/kommonitor/api/importer"
    security:
      client-id: kommonitor-importer
      secret: secret
keycloak:
  enabled: true
  realm: kommonitor
  auth-server-url: http://keycloak:8080
  resource: kommonitor-importer
springdoc:
  swagger-ui:
    config-url: /kommonitor/api/importer/v3/api-docs/swagger-config
    url: /kommonitor/api/importer/v3/api-docs
    path: /api-docs
    oauth2RedirectUrl:  http://localhost/kommonitor/api/importer/swagger-ui/oauth2-redirect.html
    oauth:
      clientId: kommonitor-importer
      clientSecret: importer-secret

# Set a proxy for geocoder requests
#proxy:
#  host: host.to.proxy
#  port: 8080