server:
  port: 8087
  contextPath: /import
spring:
  application:
    name: kommonitor-import-api
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
logging:
  level:
    org.n52.kommonitor: DEBUG
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
kommonitor:
  importer:
    datamanagement-api-url: "http://localhost:8085/management"
    fileStorageLocation: "/tmp/kommonitor"