server:
  port: 8087
spring:
  application:
    name: kommonitor-import-api
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    pathpattern:
      matching-strategy: ant_path_matcher  
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
    session:
      timeout: 1m
logging:
  level:
    org.n52.kommonitor: DEBUG
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
kommonitor:
  importer:
    datamanagement-api-url: "http://localhost:8085/management"
    geocoder-api-url: "https://geocoder.fbg-hsbo.de/geocoder"
    file-storage-location: "/tmp/kommonitor"
  swagger-ui:
    # base-path: /importer
    # do not use real values in production environment!!!
    security:
      client-id: kommonitor-importer
      secret: q4Ny6Q1R3XA4Fr0YtTt7hw0XnQasQ2Xc
keycloak:
  enabled: true
  realm: kommonitor-gib
  auth-server-url: http://localhost:8090/auth
  resource: kommonitor-importer
  bearer-only: true
  autodetect-bearer-only: false
  ssl-required: external
  public-client: false
  credentials:
    secret: q4Ny6Q1R3XA4Fr0YtTt7hw0XnQasQ2Xc
  cors: true
  cors-allowed-methods: "*"
  securityConstraints[0]:
    authRoles[0]: "*"
    securityCollections[0]:
      name: protected
      patterns[0]: /importer/*