server:
  port: 8087
spring:
  application:
    name: kommonitor-import-api
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    pathpattern:
      matching-strategy: ant_path_matcher  
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
    session:
      timeout: 1m
logging:
  level:
    org.n52.kommonitor: DEBUG
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
kommonitor:
  importer:
    datamanagement-api-url: "http://localhost:8085/management"
    geocoder-api-url: "https://geocoder.fbg-hsbo.de/geocoder"
    file-storage-location: "/tmp/kommonitor"
  swagger-ui:
    # Use the next two parameters if you run the API behind a reverse proxy
    # Host address of the reverse proxy
    #host: localhost
    # Path mapping for this API in the reverse proxy
    #base-path: /kommonitor/api/importer
    security:
      client-id: kommonitor-importer
      secret: secret
keycloak:
  enabled: true
  realm: kommonitor
  auth-server-url: http://localhost:8080
  resource: kommonitor-importer
  bearer-only: true
  autodetect-bearer-only: false
  ssl-required: external
  public-client: false
  credentials:
    secret: secret
  cors: true
  cors-allowed-methods: "*"
  securityConstraints[0]:
    authRoles[0]: "*"
    securityCollections[0]:
      name: protected
      patterns[0]: /importer/*
# Set a proxy for geocoder requests
#proxy:
#  host: host.to.proxy
#  port: 8080