/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.n52.kommonitor.importer.api;

import org.n52.kommonitor.importer.models.ConverterType;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-02T13:41:56.747+01:00")

@Api(value = "converters", description = "the converters API")
public interface ConvertersApi {

    @ApiOperation(value = "Retreive information about the selected converters", nickname = "getConverterByName", notes = "Retrieve information such like supported formats and decoding options about the selected converters for decoding a certain dataset and importing it into the KomMonitor Data Management layer", response = ConverterType.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "converters", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ConverterType.class),
        @ApiResponse(code = 400, message = "Invalid status value"),
        @ApiResponse(code = 401, message = "API key is missing or invalid") })
    @RequestMapping(value = "/converters/{name}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ConverterType> getConverterByName(@ApiParam(value = "unique name of the converter",required=true) @PathVariable("name") String name);


    @ApiOperation(value = "Retrieve information about all available converters", nickname = "getConverters", notes = "Retrieve information such like supported formats and importing options about all available converters for decoding datasets and importing them into the KomMonitor Data Management layer", response = ConverterType.class, responseContainer = "List", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "converters", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ConverterType.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid status value"),
        @ApiResponse(code = 401, message = "API key is missing or invalid") })
    @RequestMapping(value = "/converters",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<ConverterType>> getConverters();

}
