swagger: '2.0'
info:
  description: "erster Entwurf einer Daten-Import-API, die den Import räumlicher Daten (SpatialUnits, Georesources und Indicators) von beliebigen Datenquellen und Koordinatenreferenzsystemen ermöglicht."
  version: "0.0.1"
  title: "KomMonitor Data Import API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "christian.danowski-buhren@hs-bochum.de"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8087"
basePath: "/import"
tags:
- name: "spatial-units"
  description: "spatial units/levels, for which indicators can be associated (e.g. rastercells, building blocks, quarters, city districts, city boroughs, city)"
- name: "georesources"
  description: "Georesource necessary for the computation of indicators (e.g. land use, locations of schools, streets/ways)"
- name: "indicators"
  description: "indicators"
schemes:
- "http"
- "https"
securityDefinitions:
   basicAuth:
     type: basic

security:
  - basicAuth: []

paths:

  /spatial-units:
    post:
      tags:
      - "spatial-units"
      summary: "Import a new spatial-unit"
      description: "Import a new spatial unit for a certain period of time. Parses Input source, extracts relevant data, performs schema mapping to KomMonitor data model and calls POST /spatial-units of KomMonitor Data Management API"
      operationId: "importSpatialUnit"
      consumes:
      - "application/json"
      parameters:
      - name: "feature-data"
        in: "body"
        description: "feature data"
        required: true
        schema:
          $ref: "./definitions.yaml#/definitions/Import_SpatialUnitPOSTInputType"
      responses:
        201:
          description: "Created"
          headers:
            location:
              type: string
              description: identifier of the created spatial unit resource
        401:
          $ref: "#/responses/UnauthorizedError"
        405:

  ########## GEO RESOURCES
  /georesources:
    post:
      tags:
      - "georesources"
      summary: "Import a new geo-resource"
      description: "Import a geo-resource dataset for a certain period of time. Parses Input source, extracts relevant data, performs schema mapping to KomMonitor data model and calls POST /georesources of KomMonitor Data Management API"
      operationId: "importGeoresource"
      consumes:
      - "application/json"
      parameters:
      - name: "feature-data"
        in: "body"
        description: "feature data"
        required: true
        schema:
          $ref: "./definitions.yaml#/definitions/Import_GeoresourcePOSTInputType"
      responses:
        201:
          description: "Created"
          headers:
            location:
              type: string
              description: identifier of the created geo-resource resource
        401:
          $ref: "#/responses/UnauthorizedError"
        405:
          description: "Invalid input"

######## INDICATORS
  /indicators:
      post:
        tags:
        - "indicators"
        summary: "Import a new indicator dataset"
        description: "Import an indicator dataset for a certain period of time and spatial unit/level. Parses Input source, extracts relevant data, performs schema mapping to KomMonitor data model and calls POST /indicators of KomMonitor Data Management API"
        operationId: "importIndicator"
        consumes:
        - "application/json"
        parameters:
        - name: "indicator-data"
          in: "body"
          description: "indicator data"
          required: true
          schema:
            $ref: './definitions.yaml#/definitions/Import_IndicatorPOSTInputType'
        responses:
          201:
            description: "Created"
            headers:
              location:
                type: string
                description: identifier of the created indicator
          405:
            description: "Invalid input"

responses:
  UnauthorizedError:
    description: API key is missing or invalid
    headers:
      WWW_Authenticate:
        type: string

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
